"""create creatures table

Revision ID: 058b4b1b2782
Revises: 
Create Date: 2026-01-31 10:14:35.425571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058b4b1b2782'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Creatures table Database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('types', sa.Text(), nullable=False),
    sa.Column('stats', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Creatures table Database')
    # ### end Alembic commands ###
